# Use this file to set project specific config
user:
  keyboard_layouts: en,de

settings:
  system:
    use_proxy: false

box:
  name: cloud-photo-safari
  usb2: true
  memory: 4096
  cpus: 4
  monitorcount: 1
  portforwardings:
    - name: nodejs
      protocol: tcp
      host_port: 3000
      guest_port: 3000

ansible:
  # Roles to install
  roles: ["nodejs", "atom", "eclipse"]
